ROUTES = {
    "GET /manage/lessons": ("content_api.services.lessons.list_management", ("editor", "admin")),
    "GET /manage/programs": ("content_api.services.programs.list_management", ("editor", "admin")),
    "GET /manage/programs/{programId}": ("content_api.services.programs.get_management", ("editor", "admin")),
    "GET /lessons": ("content_api.services.lessons.list_published", ("reader", "editor", "admin")),
    "GET /lessons/{lessonId}": ("content_api.services.lessons.get_published", ("reader", "editor", "admin")),
    "GET /programs": ("content_api.services.programs.list_published", ("reader", "editor", "admin")),
    "GET /programs/{programId}": ("content_api.services.programs.get_published", ("reader", "editor", "admin")),
    "GET /references": ("content_api.services.references.list_published", ("reader", "editor", "admin")),
    "GET /references/{referenceId}": ("content_api.services.references.get_published", ("reader", "editor", "admin")),
    "POST /manage/lessons": ("content_api.services.lessons.create_draft", ("editor", "admin")),
    "PUT /manage/lessons/{lessonId}/draft": ("content_api.services.lessons.save_draft", ("editor", "admin")),
    "POST /manage/lessons/{lessonId}/publish": ("content_api.services.lessons.publish", ("editor", "admin")),
    "DELETE /manage/lessons/{lessonId}": ("content_api.services.lessons.archive", ("editor", "admin")),
    "POST /manage/lessons/{lessonId}/restore": ("content_api.services.lessons.restore", ("editor", "admin")),
    "GET /manage/lessons/{lessonId}": ("content_api.services.lessons.get_management", ("editor", "admin")),
    "POST /manage/lessons/{lessonId}/media-upload-url": ("content_api.services.media.issue_upload_url", ("editor", "admin")),
    "POST /manage/programs": ("content_api.services.programs.create_draft", ("editor", "admin")),
    "PUT /manage/programs/{programId}/draft": ("content_api.services.programs.save_draft", ("editor", "admin")),
    "POST /manage/programs/{programId}/publish": ("content_api.services.programs.publish", ("editor", "admin")),
    "DELETE /manage/programs/{programId}": ("content_api.services.programs.archive", ("editor", "admin")),
    "POST /manage/programs/{programId}/restore": ("content_api.services.programs.restore", ("editor", "admin")),
    "GET /manage/references": ("content_api.services.references.list_management", ("editor", "admin")),
    "GET /manage/references/{referenceId}": ("content_api.services.references.get_management", ("editor", "admin")),
    "POST /manage/references": ("content_api.services.references.create_draft", ("editor", "admin")),
    "PUT /manage/references/{referenceId}/draft": ("content_api.services.references.save_draft", ("editor", "admin")),
    "POST /manage/references/{referenceId}/publish": ("content_api.services.references.publish", ("editor", "admin")),
    "DELETE /manage/references/{referenceId}": ("content_api.services.references.archive", ("editor", "admin")),
    "POST /manage/references/{referenceId}/restore": ("content_api.services.references.restore", ("editor", "admin")),
}
